### ISSUE TITLE
Improve the installation instructions

### ISSUE THREAD

**Issue by QuingKhaos** [pixelart/swiftmailer-manipulator-bundle#5]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | no |

The installation should remain part of the README, but the further configuration should be extracted into extensive docs, e.g. below `Resources/doc/` as the [Symfony Best Practices for Reusable Bundles](https://symfony.com/doc/current/bundles/best_practices.html#documentation) recommends.

Maybe in the README a full configuration example should still be there.

**Comment by ivydigitalstorm** [comment]
@patkar i can take a look 🎃
